services:
  db-maker-menu:
    image: postgres:16.3
    container_name: db-maker-menu
    hostname: db-maker-menu
    environment:
      POSTGRES_DB: maker-menu-dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Dimik2001.
    ports:
      - "5432:5432"
    networks:
      - pizza

  maker-menu:
    image: pizza-project/maker-menu:0.0.1-SNAPSHOT
    container_name: maker-menu
    environment:
      - EUREKA_INSTANCE_HOSTNAME=eureka
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-maker-menu/maker-menu-dev
      - SPRING_LIQUIBASE_CHANGE-LOG=classpath://db/migrations/changeLog.xml
    depends_on:
      - db-maker-menu
    ports:
      - "8083:8083"
    networks:
      - pizza
networks:
  pizza:
    driver: bridge