server:
  port: 8083
spring:
  application:
    name: maker-menu
  profiles:
    active: dev
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:testDB
    password: sa
    username: password
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: always
      schema-locations: classpath:static/scripts/schema/import_*_schema.sql
      data-locations: classpath:static/scripts/data/import_*_data.sql

---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/maker-menu
    username: postgres
    password: Dimik2001.
    driver-class-name: org.postgresql.Driver