create table product_type
(
    id   int primary key generated by default as identity,
    type varchar
);

create table ingredient
(
    id int primary key generated by default as identity ,
    title varchar,
    min_weight int
);

truncate table product_type;
insert into product_type(type) values ('PIZZA');